server:
  port: 9090
spring:
  application:
    name: first-project
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_first
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

app:
  files:
    baseFolder: /root/files